### ISSUE TITLE
Store query data in autoPay to reduce steps required to get new data reported?

### ISSUE THREAD

**Issue by oraclown** [tellor-io/autoPay#49]
If reporters could run a contract function to get the query data for any funded feeds, then they could decode that query data for the query parameter values. With those they could see what data sources they need to use for reporting the query's required response. Would this reduce centralization because people wouldn't have to register queryIds somewhere?

**Comment by tkernell** [comment]
This is relevant to our planned decentralization of the dataSpecs. I think the structure is TBD, but we'll have to deal with the tradeoffs between expensive on-chain storage and decentralization. My opinion is that we ought to use an on-chain registry on eth mainnet which links to documents on ipfs. I think the tricky part will be access control. How do you change an existing query type? Do you have to pay to reserve a name?
