### ISSUE TITLE
Add feed details to DataFeedFunded event.

### ISSUE THREAD

**Issue by akremstudy** [tellor-io/autoPay#54]
this could make it easier when tracking tips to be able to calculate the possibility of getting the tip.  You can get the details by calling the respective getter but this would help lower node calls. Could be in bytes: abi.encode([*details]).
There might be issues with deployed subgraphs.

**Comment by tkernell** [comment]
we could just emit the whole FeedDetails struct:

```
event DataFeedFunded(
        bytes32 _queryId,
        bytes32 _feedId,
        uint256 _amount,
        address _feedFunder,
        FeedDetails _feedDetails
    );
```
