### ISSUE TITLE
Create a generalized 'push' autopay structure

### ISSUE THREAD

**Issue by tkernell** [tellor-io/autoPay#69]
- use autopay to create a "push" oracle
- reporters don't get paid until they both report the data and push the data to the user's contract
- does this go in a new autopay contract, or in the current main one?

**Comment by Ibrahim7388** [comment]
<details><summary>Details</summary>
<p>



</p>
</details>

**Comment by Ibrahim7388** [comment]
#76

**Comment by Ibrahim7388** [comment]
[Uploading Blockchain-in-Developing-Countries.pdf…]()

**Comment by Ibrahim7388** [comment]
[Blockchain-in-Developing-Countries.pdf](https://github.com/tellor-io/autoPay/files/11193215/Blockchain-in-Developing-Countries.pdf)

**Comment by Ibrahim7388** [comment]
#33

**Comment by Ibrahim7388** [comment]
1. 

- [ ] ### 

> ****

**Comment by Ibrahim7388** [comment]
> * use autopay to create a "push" oracle
> * reporters don't get paid until they both report the data and push the data to the user's contract
> * does this go in a new autopay contract, or in the current main one?

**Comment by Ibrahim7388** [comment]
- [ ] 

>
