### ISSUE TITLE
Contract for estimating a tip amount

### ISSUE THREAD

**Issue by tkernell** [tellor-io/autoPay#70]
- is it possible to estimate the tip amount on chain? User contracts could use it whenever they need to request a new value

**Comment by themandalore** [comment]
I think it's more like gas.  You don't need it automated.  As time goes on and you get a lot of tips, the estimators will get better and tools for submitting faster, but even with gas, there's always likely an amount above the actual amount you needed to pay

**Comment by brendaloya** [comment]
Addressed off chain: https://github.com/tellor-io/auto-tipper-bot
