### ISSUE TITLE
Feature: Modify setupDataFeed() to support dynamic reward tips based on gas price at the time of the event

### ISSUE THREAD

**Issue by AslanGoldenhour** [tellor-io/autoPay#75]
**Current State:**
I setup a data feed and specify the reward as a fixed about of TRB token. When setting up a data feed reward my thought pattern is, "What is the price of TRB today?" and "What is the average cost of gas for a transaction today?" And then I set the reward as:
`reward = average cost of gas / spot price of TRB`

**Problem**
The value of TRB is not constant relative to the value of the gas token. So this system disincentivizes data feed sponsors from funding feeds with large amounts of TRB because reporters will be overpaid when the value of TRB rises and underpaid when the value of TRB falls.

**Solution**
Allow the _reward parameter to function as a reward multiplier (a percentage) above gas cost in USD. For example, 20% above gas. 

**Game Theory Impact**
Rewarders will sort the reporting opportunities based on the reward percentage and not worry about the price of TRB relative to gas costs. The feeds offering higher margins above gas costs will be reported before the feeds offering lower margins above gas costs.

**Competitive Value** 
Chainlink, as an example, does not operate this way and so there may be opportunity to leverage this feature as a differentiator to incentivize developer adoption of Tellor as a more cost-effective oracle.

**Technical Implementation**
I'm not 100% familiar with autoPay, but I suspect that a transaction hash is known whenever a reporter claims a tip. Using that transaction hash, the autoPay codebase could use the following calculation to determine the tip payout in TRB: 
`tip in TRB = (gas cost in [MATIC,ETH,...] * spot price of [MATIC,ETH,...] * (1 + reward multiplier)) / spot price of TRB`

Alternatively, if the exact gas costs are not available, the estimated gas costs could be used by leveraging an RPC endpoint.

**Comment by oraclown** [comment]
@AslanGoldenhour Thanks for this issue!

Is it a negative that with that change^ there would be some circular reporting dependency? You need the spot price of your chain's currency, and in order to keep funding spot price reports of those values you need the spot price of your chain's currency...? Not sure if that would be a problem.

**Comment by themandalore** [comment]
yeah we've looked into this and the big drawback is that gas prices aren't really available.  Our reporters tend to race, so they're gas is traditionally higher.  We thought about having them report the gas price with each query, but that adds a whole bunch of extra data and gas.  tbh, the whole system works well on chains with super low prices (e.g. polygon where you don't care if you overpay by 50% bc it's a quarter) or with the Time based rewards.  With the time based rewards, you'd just expect to tip under then have time based rewards cover the extra bit to push you over to profitability.  But either way, a super volatile Tellor price is rough and any autopay shouldn't be too long given that

**Comment by brendaloya** [comment]
Addressed off-chain: https://github.com/tellor-io/auto-tipper-bot
